name: staging_env
channels:
  - defaults
dependencies:
  - python=3.12
  - conda-forge::ome-types=0.5.2
  - numpy
  - conda-forge::tifffile
  - pandas
  - conda-forge::beautifulsoup4
  - anaconda::scikit-image
  - pip:
    - "BaSiCPy"
    - "macsima2mc"
